<?php  exit();
/*
Page: /
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-11-27 19:31:43
*/
?>
<?php  exit();
/*
Page: /ty_adm/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-12-02 16:03:06
*/
?>
<?php  exit();
/*
Page: /ty_adm/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-12-02 16:03:56
*/
?>
<?php  exit();
/*
Page: /ty_adm/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-12-02 16:04:44
*/
?>
<?php  exit();
/*
Page: /ty_adm/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-12-02 16:05:02
*/
?>
<?php  exit();
/*
Page: /ty_adm/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-12-02 16:05:43
*/
?>
<?php  exit();
/*
Page: /ty_adm/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-12-02 16:06:00
*/
?>
<?php  exit();
/*
Page: /ty_adm/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-12-02 16:07:12
*/
?>
