<div class="pd_jbfl z">

      <div class="p4z_tt tb4_">

        <h3 class="wt z"><a href="{dede:field name='typeurl'/}">{dede:field.seotitle /}</a></h3>

      </div>

      <ul>

        <li class="li2">{dede:arclist row='1' titlelen='20' infolen='100' flag=''} <a href="[field:arcurl/]" target="_blank" title="[field:fulltitle/]"><img src="[field:litpic/]" /></a><strong> <a  href="[field:arcurl/]" target="_blank" title="[field:fulltitle/]">[field:title/]</a></strong><br />

          [field:infos/]... <a  href="[field:arcurl/]" target="_blank" title="[field:fulltitle/]" class="red">ฯ๊ว้>></a> {/dede:arclist} </li>

        {dede:arclist row='4' titlelen='60' flag=''}

        <li> <a  href="[field:arcurl/]" target="_blank" title="[field:fulltitle/]">[field:title/]</a> </li>

        {/dede:arclist}

      </ul>

    </div>