<dl>             
					<dt><img src="[field:litpic/]" style="width:102px;height:117px;"></dt>
					<dd>                  
						<b>[field:title/]</b>
						<h4>[field:infos/]<a href="[field:arcurl/]" target="_blank">¡¾ÏêÏ¸¡¿</a></h4>
						<span><a href="/swt/" target="_blank"><img src="/images/right/zxuna01.jpg" /></a></span>
						<span><a href="/swt/" target="_blank"><img src="/images/right/zxuna02.jpg" /></a></span>
					</dd>
				</dl>