<a href="/zjtd/huyingzhou.html" target="_blank"><img src="/uploads/allimg/131104/3-131104135155519.jpg"></a>
            <h4><a href="/zjtd/huyingzhou.html">胡瀛洲</a></h4>
            <h5>
				<span>医生职称：</span>院长&nbsp;&nbsp;<span>从医时间：</span>40余年<br>
				<span> 医学擅长：</span>颈椎病、腰椎间盘突出、骨质疏松、股骨头无菌性坏死<br>
            </h5>
            <p><span>名医简介：</span>现任成都西南骨科医院院长，从事骨科临床、教学、科研、及康复工作40余年，积累了丰富的中医临床、教学和科研经验。尤其以治疗各种类型颈椎病，腰椎间盘突出...<a href="/zjtd/huyingzhou.html" target="_blank">[详细]</a></p>
            <h6><a href="/swt"><img src="/images/zxan1.gif"></a><a href="/swt"><img src="/images/zxan2.gif"></a></h6>
          </div>
    
    <div class="chd">

      <div class="huandeng">

        <div class="huandeng_img"> </div>

        <embed src="http://static.youku.com/v1.0.0149/v/swf/qplayer.swf?VideoIDS=XNTk2MjYwNzg0&winType=adshow&isAutoPlay=false" quality="high" width="278" height="228" align="middle" allowscriptaccess="never" allownetworking="internal" autostart="false" type="application/x-shockwave-flash">

      </div>

      

      <!-----------图片切换  end-----------> 

      

    </div>

    <div style="clear:both; height:0"></div>

  </div>

</div>

<div class="ctop4">

  <div class="list"> {dede:list pagesize='10' orderby='weight'}

    <div class="list1">

      <h1><a href="[field:arcurl/]">[field:title/]</a></h1>

      <img src="[field:litpic/]" />

      <p style=" padding-top:0;">[field:description/]…<a href="[field:arcurl/]">[详细]</a></p>

    </div>

    {/dede:list}

    <div class="page">

      <ul>

        {dede:pagelist listitem="info,index,end,pre,next,pageno,option" listsize="5"