<h1><a href="[field:typelink/]">就诊指南</a><span> <a target="_blank" href="[field:typelink/]"><img width="37" height="13" src="/images/dggc_168.png"></a> </span></h1>
      <div class="map">
	  <a target="_blank " href="[field:typelink/]"> <img src="/images/ditu1.jpg" width="216" height="132"></a>

        <p><strong>医院地址：</strong>成都市武侯大道双楠段38号<br>

          <strong>咨询电话：</strong>028-85596750<br>

          <em>请提前网络咨询预约（无假日医院）</em></p>

      </div>

    </div>