<a target="_blank" href="[field:typelink/]">
			<div style="background:url(/images/banner2_01.jpg) top center no-repeat; width:100%; height:76px;"></div>
			<div style="background:url(/images/banner2_02.jpg) top center no-repeat; width:100%; height:99px;"></div>
			<div style="background:url(/images/banner2_03.jpg) top center no-repeat; width:100%; height:76px;"></div>
			<div style="background:url(/images/banner2_04.jpg) top center no-repeat; width:100%; height:99px;"></div>
		 </a>