<div class="p8y_tt wt"><a href="[field:typelink/]" target='_blank'>来院路线</a></div>

      <div class="p8y_b"> <a href='[field:typelink/]' target=_blank><img src="/images/laiyuanlx01.jpg" alt='来院地图' style="width:248px;height:91px;"/></a>

        <p> <b>医院地址：</b>成都市武侯大道双楠段38号<br />

          <b>咨询电话：</b><span class="red">028-85596750</span><br />

          <span class="red bl">就诊前请提前网络咨询预约</span>（无假日医院) </p>

      </div>

    </div>