<a target="_blank" href="/html/zjwd/">
		<img src="/images/dggc_zjwd_l.jpg" width="580" height="51" border="0" />
	  </a>
	{}
	  <a target="_blank" href="/swt/">
		<img  src="/images/dggc_zjwd_r.gif"  width="394" height="51" border="0"/>
	  </a>
  <span class="yuyue11"><script type="text/javascript" src="/js/yy1.js"></script></span>
  </p>
  <div class="con">
  <!--left start-->
         <div class="zjwd_left">
        <div class="hd">
          <ul>
            <li>风湿性关节炎</li>
            <li>类风湿性关节炎</li>
            <li>滑膜炎</li>
            <li>痛风</li>
            <li>产后风湿</li>
          </ul>
        </div>
        <div class="bd">
          <div class="ulWrap">
            <ul>
              {dede:arclist typeid='61' row='9' titlelen='80' orderby='weight'  }
              <li><a href="[field:arcurl /]" target="_blank"><font color="#CC0000">[field:shorttitle/]:&#160;</font>[field:title /]</a><span>专家已回复</span></li>
              {/dede:arclist}
            </ul>
            <ul>
              {dede:arclist typeid='59' row='9' titlelen='80' orderby='weight'  }
              <li><a href="[field:arcurl /]" target="_blank"><font color="#CC0000">[field:shorttitle/]:&#160;</font>[field:title /]</a><span>专家已回复</span></li>
              {/dede:arclist}
            </ul>
            <ul>
              {dede:arclist typeid='65' row='9' titlelen='80' orderby='weight'  }
              <li><a href="[field:arcurl /]" target="_blank"><font color="#CC0000">[field:shorttitle/]:&#160;</font>[field:title /]</a><span>专家已回复</span></li>
              {/dede:arclist}
            </ul>
            <ul>
              {dede:arclist typeid='63' row='9' titlelen='80' orderby='weight'   }
              <li><a href="[field:arcurl /]" target="_blank"><font color="#CC0000">[field:shorttitle/]:&#160;</font>[field:title /]</a><span>专家已回复</span></li>
              {/dede:arclist}
            </ul>
            <ul>
              {dede:arclist typeid='67' row='9' titlelen='80' orderby='weight'  }
              <li><a href="[field:arcurl /]" target="_blank"><font color="#CC0000">[field:shorttitle/]:&#160;</font>[field:title /]</a><span>专家已回复</span></li>
              {/dede:arclist}
            </ul>
          </div>
        </div>
        <div style="clear:both"></div>
        <a href="/swt/" class="but" target="_blank"></a> </div>
		<!--left end-->
		

		<!--right start-->
    <div class="jzzn_right">
      <div class="jzzn_con4">
        <div class="jzzn_con4_t"><span class="yy_name_t m_l_15">姓名</span><span class="yy_bz_t m_l_20">联系电话</span><span class="yy_zj_t m_l_15">预约专家</span><span class="yy_time_t m_l_15">预约时间</span><span class="yy_zt_t m_l_15">预约状态</span></div>
        <div class="tempWrap">
          <ul>
            <li style="height: 24px;"><font class="tomorrow">预约成功</font><span class="m_l_15">赵*泽</span><span class="yy_bz m_l_20">158****2357</span><span class="yy_zj m_l_15">胡瀛洲</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d",strtotime("+1 day"));{/dede:php}</span></li>
            <li style="height: 24px;"><font class="yesterday">已就诊</font><span class="m_l_15"></span>朱*兰<span class="yy_bz m_l_20">159****7952</span><span class="yy_zj m_l_15">李连蓓</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d",strtotime("-1 day"));{/dede:php}</span></li>
            <li style="height: 24px;"><font class="yesterday">已就诊</font><span class="m_l_15">曹*&#160;&#160;</span><span class="yy_bz m_l_20">136****3158</span><span class="yy_zj m_l_15">胡瀛洲</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d",strtotime("-1 day"));{/dede:php}</span></li>
            <li style="height: 24px;"><font class="today">已就诊</font><span class="m_l_15">李*桐</span><span class="yy_bz m_l_20">138****7511</span><span class="yy_zj m_l_15">胡瀛洲</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d");{/dede:php}</span></li>
            <li style="height: 24px;"><font class="yesterday">已就诊</font><span class="m_l_15">王*航</span><span class="yy_bz m_l_20">136****8399</span><span class="yy_zj m_l_15">胡瀛洲</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d",strtotime("-1 day"));{/dede:php}</span></li>
            <li style="height: 24px;"><font class="tomorrow">预约成功</font><span class="m_l_15">武*&#160;&#160;</span><span class="yy_bz m_l_20">152****7592</span><span class="yy_zj m_l_15">李连蓓</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d",strtotime("+1 day"));{/dede:php}</span></li>
            <li style="height: 24px;"><font>预约成功</font><span class="m_l_15">张*瑞</span><span class="yy_bz m_l_20">158****8550</span><span class="yy_zj m_l_15">胡瀛洲</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d",strtotime("+1 day"));{/dede:php}</span></li>
            <li style="height: 24px;"><font class="today">已就诊</font><span class="m_l_15">方*涵</span><span class="yy_bz m_l_20">189****5927</span><span class="yy_zj m_l_15">胡瀛洲</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d");{/dede:php}</span></li>
            <li style="height: 24px;"><font class="today">已就诊</font><span class="m_l_15">吴*浩</span><span class="yy_bz m_l_20">136****4245</span><span class="yy_zj m_l_15">胡瀛洲</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d");{/dede:php}</span></li>
            <li style="height: 24px;"><font class="tomorrow">预约成功</font><span class="m_l_15">李*谦</span><span class="yy_bz m_l_20">151****3155</span><span class="yy_zj m_l_15">秦立范</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d",strtotime("+1 day"));{/dede:php}</span></li>
            <li style="height: 24px;"><font class="yesterday">已就诊</font><span class="m_l_15">王*&#160;&#160;</span><span class="yy_bz m_l_20">159****8562</span><span class="yy_zj m_l_15">胡瀛洲</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d",strtotime("-1 day"));{/dede:php}</span></li>
            <li style="height: 24px;"><font class="yesterday">已就诊</font><span class="m_l_15">艾*森</span><span class="yy_bz m_l_20">159****2911</span><span class="yy_zj m_l_15">李连蓓</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d",strtotime("-1 day"));{/dede:php}</span></li>
            <li style="height: 24px;"><font class="yesterday">已就诊</font><span class="m_l_15">张*良</span><span class="yy_bz m_l_20">151****7458</span><span class="yy_zj m_l_15">胡瀛洲</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d",strtotime("-1 day"));{/dede:php}</span></li>
            <li style="height: 24px;"><font>预约成功</font><span class="m_l_15">刘*扬</span><span class="yy_bz m_l_20">180****5633</span><span class="yy_zj m_l_15">李连蓓</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d",strtotime("+1 day"));{/dede:php}</span></li>
            <li style="height: 24px;"><font>预约成功</font><span class="m_l_15">陈*玉</span><span class="yy_bz m_l_20">159****2054</span><span class="yy_zj m_l_15">胡瀛洲</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d",strtotime("+1 day"));{/dede:php}</span></li>
            <li style="height: 24px;"><font class="today">已就诊</font><span class="m_l_15">李*莲</span><span class="yy_bz m_l_20">180****9477</span><span class="yy_zj m_l_15">胡瀛洲</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d");{/dede:php}</span></li>
            <li style="height: 24px;"><font>预约成功</font><span class="m_l_15">王*迪</span><span class="yy_bz m_l_20">152****7311</span><span class="yy_zj m_l_15">李连蓓</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d",strtotime("+1 day"));{/dede:php}</span></li>
            <li style="height: 24px;"><font>预约成功</font><span class="m_l_15">史*&#160;&#160;</span><span class="yy_bz m_l_20">152****8955</span><span class="yy_zj m_l_15">胡瀛洲</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d",strtotime("+2 day"));{/dede:php}</span></li>
            <li style="height: 24px;"><font class="today">已就诊</font><span class="m_l_15">秦*华</span><span class="yy_bz m_l_20">189****5508</span><span class="yy_zj m_l_15">胡瀛洲</span><span>{dede:php  runphp='yes'}@me=date("Y-m-d");{/dede:php}</span></li>
          </ul>
        </div>
        <div class="jzzn_con5"><span><script type="text/javascript" src="/js/yy2.js"></script></span></div>
      </div>
    </div>
	<!--right end-->
    <div style="clear:both"></div>
  </div>
</div>

<div class="mainanli mg10 w980">
  <div class="anli">
    <div class="anli_tit"><a href="/kfal/" target="_blank"><img src="images/ka_tit.jpg"></a></div>
    <div class="anli_sp">
      <div class="anli_l"> {dede:arclist addfields='name,hbsj,zlsj,zysj,zlgc' channelid='18'  titlelen='27' infolen='150' typeid='11' flag='p,a' limit='0,1'}
        <li><a href="[field:arcurl/]" target="_blank"><img alt="[field:title/]" src="[field:litpic/]" width="220" height="150"></a><span><a href="[field:arcurl/]" target="_blank">[field:title/]</a></span>
          <p><b>患者姓名：</b>[field:name/]</p>
          <p><b>患病时间：</b>[field:hbsj function=MyDate('Y-m-d',@me)/]</p>
          <p><b>治疗时间：</b>[field:zlsj function=MyDate('Y-m-d',@me)/]</p>
          <p><b>治愈时间：</b>[field:zysj function=MyDate('Y-m-d',@me)/]</p>
          <p><b>治疗详情：</b>[field:info/]…<a href="[field:arcurl/]" target="_blank">【详细】</a></p>
        </li>
        {/dede:arclist} </div>
		
      <div class="anli_sp_con"> <embed src="http://ziyuan.fsb006.com/video/player_tu.swf" width="438" height="300" name="wmode" value="opaque" wmode="opaque" allowscriptaccess="always" allowfullscreen="true" flashvars="file=http://ziyuan.fsb006.com/video/xinan/ydy/ydy1.flv&image=http://ziyuan.fsb006.com/video/xinan/ydy/ydy1.jpg">         
      </div>
	  
      <div class="anli_r">{dede:arclist addfields='name,hbsj,zlsj,zysj,zlgc' channelid='18'  titlelen='25' infolen='150' typeid='11' flag='p,a' limit='1,1'}
        <li><a href="[field:arcurl/]" target="_blank"><img alt="[field:title/]" src="[field:litpic/]" width="220" height="150"></a><span><a href="[field:arcurl/]" target="_blank">[field:title/]</a></span>
          <p><b>患者姓名：</b>[field:name/]</p>
          <p><b>患病时间：</b>[field:hbsj function=MyDate('Y-m-d',@me)/]</p>
          <p><b>治疗时间：</b>[field:zlsj function=MyDate('Y-m-d',@me)/]</p>
          <p><b>治愈时间：</b>[field:zysj function=MyDate('Y-m-d',@me)/]</p>
          <p><b>治疗详情：</b>[field:info/]…<a href="[field:arcurl/]" target="_blank">【详细】</a></p>
        </li>
        {/dede:arclist} </div>
    </div>
    <div class="anli_con">
      <ul>
        {dede:arclist row='8' titlelen='36' typeid='11' flag='p' noflag='a'}
        <li><a href="[field:arcurl/]" target="_blank"><img alt="[field:fulltitle/]" src="[field:litpic/]" width="220" height="150"></a><span><a href="[field:arcurl/]" target="_blank">[field:fulltitle/]</a></span>
          <p>[field:infos/]…<a href="[field:arcurl/]" target="_blank">【详细】</a></p>
        </li>
        {/dede:arclist}
      </ul>
      <div class="clear"></div>
    </div>
  </div>
</div>
<!--案例结束--> 

<!-- <div class="w980 mg10 t_align" ><a href="/zt/yybj/" target="_blank"><img src="images/zy_banner.jpg" width="980" height="110"  border="0" /></a></div> -->


<!--文章开始-->
<div class="main_5 w980 mg10">
    <div class="nxzlzx float_l">
<div class="nxzlzx_lm">
        <p>{dede:type typeid='15'}<a href="[field:typeurl/]" title="[field:fulltitle/]" target="_blank">类风湿性关节炎</a>