<li>
          <h3><b><a href="[field:arcurl/]" target="_blank">西南骨科名医榜—[field:title/]</a></b><span><em><a href="[field:arcurl/]" target="_blank">详细>></a></em></span></h3>
          <div class="zj_box_pic"> <a href="[field:arcurl/]" target="_blank"><img  src="[field:litpic/]"></a></div>
		  <div class="zj_box_right">
            <h4><a href="[field:arcurl/]">[field:title/]</a></h4>
            <span class="zj_box_right_t">医生职称：</span><span class="zj_box_right_c">院长</span><span class="zj_box_right_t">从医时间：</span><span class="zj_box_right_c">40余年</span><br>
            <span class="zj_box_right_t">医学擅长：</span><span class="zj_box_right_c">颈椎病、腰椎间盘突出、骨质疏松、股骨头无菌性坏死</span><br>          
            <p ><span>名医简介：</span><span class="zj_box_right_c">[field:description function="cn_substr(@me,130)"/]...<a href="[field:arcurl/]" target="_blank">[详细]</a></span></p>
            <div class="zj_box_right_swt"><a href="/swt"><img src="/images/zxan1.gif"></a><a href="/swt"><img src="/images/zxan2.gif"></a></div>
		</div>
        <div style="clear:both"></div>
        </li>