<field:name itemname="姓名" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:name>

<field:sexy itemname="性别" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="男,女"  maxlength="250" page="">
</field:sexy>

<field:age itemname="年龄" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:age>

<field:jibing itemname="所患疾病" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jibing>
<field:hbsj itemname="患病时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hbsj>
<field:zlsj itemname="治疗时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zlsj>
<field:zysj itemname="治愈时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zysj>
<field:dbpic itemname="治疗对比图" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dbpic>
<field:zlzj itemname="治疗专家" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zlzj>
<field:zlgc itemname="治疗过程" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zlgc>
<field:hzzs itemname="患者自述" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hzzs>
<field:hzpj itemname="患者评价" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hzpj>