<li><a href="[field:arcurl/]" target="_blank"><img alt="[field:title/]" src="[field:litpic/]" width="220" height="150"></a><span><a href="[field:arcurl/]" target="_blank">[field:title/]</a></span>
          <p><b>患者姓名：</b>[field:name/]</p>
          <p><b>患病时间：</b>[field:hbsj function=MyDate('Y-m-d',@me)/]</p>
          <p><b>治疗时间：</b>[field:zlsj function=MyDate('Y-m-d',@me)/]</p>
          <p><b>治愈时间：</b>[field:zysj function=MyDate('Y-m-d',@me)/]</p>
          <p><b>治疗详情：</b>[field:zlgc/]…<a href="[field:arcurl/]" target="_blank">【详细】</a></p>
        </li>