<p class="p5_p1"> <span><font>胡瀛洲</font> [field:zhicheng/]</span>简介：[field:info/]...<a href="[field:arcurl/]" target="_blank">[查看详细]</a> <span style="padding-top:10px"><img src="images/cbjsp.png" border="0" usemap="#cbj" />
        <map name="cbj" id="cbj">
          <area shape="rect" coords="2,2,115,32" href="/swt/" target="_blank" alt="点击咨询" />
          <area shape="rect" coords="124,2,253,33" href="/swt/" target="_blank" alt="在线预约">
        </map>
        </span> </p>
      <a href="[field:arcurl/]" target="_blank" class="p5_a1"></a>
      <p class="p5_p2">胡瀛洲院长友情提醒各位患者，治疗强直性脊柱炎已经不再是医学难题，请各位患者保持良好的心态，不要自暴自弃。我们的"生物免疫平衡多元疗法"一定能帮大家解除病痛，还大家一个健康的身体！</p>