<a href="[field:typeurl/]" target="_blank">常识</a></li>
            <li><a href="/swt/" target="_blank" style="color:#F00">咨询专家</a></li>
          </ul>
        </div>
        <div id="ccccccc01">
		{dede:arclist row='1' titlelen='22' infolen='70' typeid='20' flag='h'}
          <p><img src="[field:picname/]" width="96" height="113" /></p>
          <dl>
            <dt><a href="[field:arcurl/]" target="_blank">[field:title/]</a></dt>
            <dd>[field:info/]...<a class="xx_hs" href="[field:arcurl/]" target="_blank">[详细]</a></dd>
          </dl>
		{/dede:arclist}
          <ul>
		  {dede:arclist }
            <li class="style6"><a href="http://qz.shzzyy2013.com/qzxjzyzz/416.html" target="_blank">强直性脊柱炎症状表现是什么</a></li>
			{/dede:arclist}
            <li class="style5"><a href="http://qz.shzzyy2013.com/qzxjzyzz/290.html" target="_blank">强直性脊柱炎早中晚期症状都有</a></li>
            <li class="style6"><a href="http://qz.shzzyy2013.com/qzxjzyzz/442.html" target="_blank">如何判断是否患上强直性脊柱炎</a></li>
          </ul>
        </div>
        
      </div>
    </div>
  </div>
<!--文章板块2结束--> 

<!--底部医院四项目-->
<div class="w980 mg10 link_k">
  <div class="link_lm">
    <div class="scrollUl1" style="overflow:hidden; width:980px;">
      <ul>
        <li id="xm01" class="sd07" ><a href="/xjsb/" target="_blank">先进设备</a></li>
        <li id="xm02" class="sd08" ><a>医院环境</a></li>
        <li id="xm03" class="sd08" ><a>就诊指南</a></li>
        <li id="xm04" class="sd08" ><a>我院优势</a></li>
      </ul>
    </div>
    <div class="xc">
      <div id="xc01" class="gundong1">
        <ul>
          {dede:arclist  titlelen='20' typeid='8' }
          <li>
            <dt><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" width="198" height="110" /></a></dt>
            <dd><a href="[field:arcurl/]" target="_blank">[field:title/]</a></dd>
          </li>
          {/dede:arclist}
        </ul>
      </div>
      <div class="gundong1" id="xc02">
        <ul>
          {dede:arclist  titlelen='20' typeid='17' }
          <li>
            <dt><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" width="146" height="110" /></a></dt>
            <dd><a href="[field:arcurl/]" target="_blank">[field:title/]</a></dd>
          </li>
          {/dede:arclist}
        </ul>
      </div>
      <div id="xc03" class="hidden" style="width: 980px; height: 130px; display:none">
        <ul>
          <li><a href="/lylx/"><img src="/images/ditu1.jpg" width="300" height="145"></a></li>
          <li><a href="/swt/"><img src="/images/ditu2.jpg" width="313" height="145" style=" border:#ccc 1px solid"></a></li>
          <li><a href="/swt/"><img src="/images/ditu3.jpg" width="310" height="145" style=" border:#ccc 1px solid"></a></li>
        </ul>
      </div>
      <div id="xc04" class="hidden" style="width: 980px; margin-left:-5px; display:none">
        <ul>
          <li><img src="/images/ys.jpg" width="300" height="145"></li>
          <li>
            <dt><img src="/images/ys1.jpg"></dt>
            <dt style="background-color:#fff; font-size:14px; line-height:26px">来自上海，北京等三甲医院风湿骨病骨干专家加盟</dt>
            <dt style="margin-top:10px"><img src="/images/ys2.jpg"></dt>
            <dt style="background-color:#fff;font-size:14px;line-height:26px">引进国际最新技术"AS-净骨疗法"，彻底治愈强直</dt>
          </li>
          <li>
            <dt><img src="/images/ys3.jpg"></dt>
            <dt style="background-color:#fff; font-size:14px;line-height:26px; margin-left:15px;">医院实现"一医一患"绿色通道三米微笑等人性服务</dt>
            <dt style="margin-top:10px"><img src="/images/ys4.jpg" ></dt>
            <dt style="background-color:#fff;font-size:14px;line-height:26px; margin-left:15px;">建立医患互动,术后回访机制,保证和谐医患关系</dt>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>
<div class="w980 mg10">
  <div class="yqlj">合作单位</div>
  <div class="yqlj_main" style=" width:962px; padding:10px; border: solid 1px #dedede; margin:0 auto 10px auto; background:#fff; overflow:hidden;">
    <ul>
      <li style="line-height:27px; float:left; display:inline;"> <img src="/images/hzmt.jpg" width="916" height="93" /></li>
    </ul>
  </div>
</div>
</div>
</div>
</div>
<!--中间部分结束--> 
<script language="javascript" type="text/javascript" src="http://ziyuan.fsb006.com/zhuchiren/wthvideo.js"></script> 
<script language="javascript" type="text/javascript" src="http://ziyuan.fsb006.com/zhuchiren/shqz.js"></script> 
{dede:include filename='footer_index.htm'