<div class="an_imbg">
			
				<a href="[field:arcurl/]" target="_blank"><img src="[field:picname/]"></a>
			
			</div>
            <div class="an_intro" style="display:inline;" >
			
              <h3 style="display:inline; float:left; margin:0;">姓名：<a href="[field:arcurl/]" style="color:#5A5A5A; " target="_blank">[field:title/]</a></h3>	
			
              <p class="expAskBtn" style="display:inline; float:left; padding-left:30px;"><a href="/swt/">向TA提问</a></p>
            </div>
            <p style="float:right; line-height:25px; width:520px;">简介：[field:xxjs/]</p>