<a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]"></a>
            <h4><a href="[field:arcurl/]">[field:title/]</a></h4>
            <h5>
				<span>医生职称：</span>[field:zhicheng/]&nbsp;&nbsp;<span>从医时间：</span>[field:cysj/]<br>
				<span> 医学擅长：</span>[field:shanchang/]<br>
            </h5>
            <p><span>名医简介：</span>[field:info/]...<a href="[field:arcurl/]" target="_blank">[详细]</a></p>
            <h6><a href="/swt"><img src="/images/zxan1.gif"></a><a href="/swt"><img src="/images/zxan2.gif"></a></h6>