<li>
          <h3><b><a href="[field:arcurl/]" target="_blank">西南骨科名医榜—[field:title/]</a></b><span><em><a href="[field:arcurl/]" target="_blank">详细>></a></em></span></h3>
          <div class="zj_list_js"> <a href="[field:arcurl/]" target="_blank"><img  src="[field:litpic/]"></a>
            <h4><a href="[field:arcurl/]">[field:title/]</a></h4>
            <h5><span>医生职称：</span>院长&#160;&#160;<span>从医时间：</span>40余年<br>
             <span> 医学擅长：</span>颈椎病、腰椎间盘突出、骨质疏松、股骨头无菌性坏死<br>
            </h5>
            <p><span>名医简介：</span>[field:description function="cn_substr(@me,130)"/]...<a href="[field:arcurl/]" target="_blank">[详细]</a></p>
            <h6><a href="/swt"><img src="/images/zxan1.gif"></a><a href="/swt"><img src="/images/zxan2.gif"></a></h6>
          </div>
        </li>