<dl>
        <dt><img src="[field:picname/]" style="width:102px;height:117px;"></dt>
        <dd> <b>║·хн╓▐ ╘║│д</b>
          <h4>[field:zzjj function()]...<a href="/html/zjtd/37.html" target="_blank">б╛╧ъ╧╕б┐</a></h4>
          <span><a href="/swt/" target="_blank"><img src="/images/right/zxuna01.jpg" /></a></span> <span><a href="/swt/" target="_blank"><img src="/images/right/zxuna02.jpg" /></a></span> </dd>
      </dl>