<li>
          <h3><b><a href="[field:arcurl/]" target="_blank">西南骨科名医榜—[field:title/]</a></b><span><em><a href="[field:arcurl/]" target="_blank">详细&gt;&gt;</a></em></span></h3>
		  
          <div class="zj_list_js">
	<div style="float:left; height:180px;">		  
		  <a href="[field:arcurl/]" target="_blank"><img src="[field:picname/]"></a>
	</div>
	<div style="float:left; height:180px;">
            <h4><a href="[field:arcurl/]">[field:title/]</a></h4>
            <h5><span>医生职称：</span>[field:zhicheng/]&nbsp;&nbsp;<span>从医时间：</span>[field:cysj/]<br>
             <span> 医学擅长：</span>[field:shanchang/]<br>
            </h5>
            <p><span>名医简介：</span>[field:zzjj/]...<a href="[field:arcurl/]" target="_blank">[详细]</a></p>
	
            <h6><a href="/swt"><img src="/images/zxan1.gif"></a><a href="/swt"><img src="/images/zxan2.gif"></a></h6>
	</div>
          </div>
        </li>