<div class="an_imbg">
			
				<a href="[field:arcurl/]" target="_blank"><img src="[field:picname/]"></a>
			
			</div>
            <div class="an_intro" style="display:inline;" >
			
              <h3 style="display:inline; float:left; margin:0;">姓名：<a href="[field:arcurl/]" style="color:#5A5A5A; " target="_blank">[field:title/]</a></h3>	
			
              <p class="expAskBtn" style="display:inline; float:left; padding-left:30px;"><a href="/swt/">向TA提问</a></p>
            </div>
            <p style="float:right; line-height:25px; width:520px;">简介：胡瀛洲【专业特长】四川大学华西医院骨科胡瀛洲教授，主任医生，博士研究生导师。一直在骨科临床，科研和教学的第一线作实际工作。曾任中华医学会骨肿瘤学组副组长，中国脊柱脊髓损伤专委会常委，中国抗癌协会肉瘤专委会常委，四川省骨科专委会主任委员、骨肿瘤骨病学术组组长，骨质疏松专委会副主任委员。中国脊柱脊髓杂志、中国骨与关节杂志、四川医学杂志、临床骨科杂志、中国罕少病杂志编委。曾赴美国、德国、法国、韩国和香港参加骨科学术交流，在中华系列杂志发表骨科论著30余篇，参加编著《骨科正误》、《中西结合肿瘤防治手册》、《脊柱外科手术学》、《骨科手术学》、《骨科手术图解》、《修复重建外科学》、《新编实用骨科学》、《骨科康复学》。获省、部级科技进步奖数项。</p>