<li class="li2">
          <div style="width:100%;">
            <h3><a href="[field:arcurl/]" target="_blank" title="[field:title/]">[field:title/]</a></h3>
          </div>
          <a href="[field:arcurl/]" target="_blank" title="[field:title/]"><img src="[field:litpic/]" width="144" height="102" title="[field:title/]"></a>
          <p>[field:description function='cn_substr(@me,106)'/]...<a href="[field:arcurl/]" target="_blank">ÏêÏ¸</a></p>
        </li>